### ISSUE TITLE
how to use it？

### ISSUE THREAD

**Issue by osmboy** [globocom/vault#12]

**Comment by alanvitor** [comment]
Actually you need Keystone to authenticate Vault with Swift service. Vault login uses the django.auth authentication with an oauth endpoint.

Still there are so many things to start from scratch, because at the beginning of Vault development we already have those services running at our stack.

We've developed new features to Vault and we want to release them in this public version as soon as possible. One of our objectives is to simplify that initial setup.

Thanks for the interest!
